# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:24


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': [],
                'managed': False,
                'permissions': [('api_access', 'Api Access')],
            },
        ),
    ]
