# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/store/img/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
