# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 22:02


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_default_price_set'),
        ('mete', '0002_add_user_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
