# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_log'),
        ('mete', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_set', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.PriceSet')),
            ],
            options={
                'permissions': [('has_api_access', 'Has API access')],
            },
        ),
    ]
