# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mete', '0006_account_is_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
    ]
