# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 22:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mete', '0008_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='categories',
            field=models.ManyToManyField(null=True, to='store.Category'),
        ),
    ]
