# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 21:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20161006_2001'),
        ('mete', '0009_auto_20161006_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mete.Account')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='store.Category'),
        ),
    ]
