# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mete', '0010_auto_20161013_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
