# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 18:01


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mete', '0011_auto_20161013_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='number',
            field=models.CharField(max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='categories',
            field=models.ManyToManyField(blank=True, to='store.Category'),
        ),
    ]
