# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_default_price_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='product',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
