# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-26 18:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20161006_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='/static/store/img/product_default.png', upload_to='products/'),
        ),
    ]
