#!/usr/bin/env python

import argparse
import requests


def retrieve_barcode(host, token, barcode):
    """Fetch associated object from server"""
    url = "{}/api/barcode/{}/".format(host, barcode)
    res = requests.get(url, headers={
        'Authorization': 'Token {}'.format(token)
    })

    return (res.json(), res.status_code == 200)


def is_account(obj):
  """Check if response is account"""
  if obj.get('username'):
    return True
  return False

def parse_arguments():
    """Get commandline arguments"""
    parser = argparse.ArgumentParser(description='Scantool Params')
    parser.add_argument('-t', '--api-token', required=True)
    parser.add_argument('-m', '--mete-host', required=True)

    return parser.parse_args()


if __name__ == '__main__':
    args = parse_arguments()

    api_token = args.api_token
    host = args.mete_host

    print("[i] Using {}".format(host))

    while True:
      barcode = raw_input()
      print("[i] Fetching: {}".format(barcode))

      result, ok = retrieve_barcode(host, api_token, barcode)
      if not ok:
        print("[e] Unknown barcode")
        continue

      if is_account(result):
        account = result
        print("[+] Hello {username}".format(**account))
      else:
        product = result
        print("[+] Checkout {name} for {price}".format(**product))
